### ISSUE TITLE
Question about categorical distribution

### ISSUE THREAD

**Issue by onnoeberhard** [APMLA-2021/APMLA-2021_material#4]
Hello, 

I have a question about the notation of categorical distributions. I am confused about the apparent difference between the following two lines:

<img width="406" alt="p(z_=_k)_ =_thet" src="https://user-images.githubusercontent.com/21868012/118029177-327bae80-b364-11eb-99d8-acd6eed28dc1.png">

I understand that z is a random variable, so it might be a bit unorthodox to write theta_z (this would obviously also be a random variable, but so is [z = k]), but it would simplify many expressions dramatically (in tutorial 2). Is this ok or is it necessary to write the expression with the product and Iverson brackets?

Kind regards,
Onno

**Comment by cdebacco** [comment]
Hi Onno,

The second line is different in the sense that it includes explicitly all of the possible value k that z can take, but the 2 expressions are equivalent. The second can make calculations easier as when you take the log you can have explicitly that only the terms where z==k are non zero. You can also re-write it as you propose, with the \theta_z, but you would need to first define it somewhere, otherwise it is not clear what theta_z is (a vector, a function, an entry of a vector?). It would be enough to state that \theta_z is defined as the left-hand-side of the second line, but in order not to confuse it with \theta_k (which can be seen as the k-th entry of the vector \theta), I would rename it with another variable name,

Caterina

**Comment by onnoeberhard** [comment]
Ok thank you!
