### ISSUE TITLE
Exam registration 

### ISSUE THREAD

**Issue by onnoeberhard** [APMLA-2021/APMLA-2021_material#5]
Dear Prof. De Bacco,

will it be possible to take the second exam instead of the first exam, i.e. register for the second one directly?
Another question, for the exam registration, do we do this by filling out the registration form and sending it by post to the examination office? (I couldn't find the digital registration on ALMA.)

Kind regards,
Onno

**Comment by cdebacco** [comment]
Yes, one can take the second instead of the first, you are free to decide which one works best for you.
As for the exam registration, I thought that the class was visible in ALMA, at least this is what the Uni admin told me (they said that is enough to register via ALMA), so if this is not the case please let me know, and I will contact them to clarify

**Comment by onnoeberhard** [comment]
I can see the lecture on ALMA, but not the exam..

**Comment by cdebacco** [comment]
Uni admin replied with this info:

"they cannot register in Alma as your lecture is not implemented in the examination system in Alma. This is the case for many lectures and no exception.
Students have to write to their respective examinations office for registering for the exam."

Let me know if there is anything else I should ask
